<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFrameworks>net8.0-windows;net481</TargetFrameworks>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationIcon>Resources\tanpopo.ico</ApplicationIcon>
    <Nullable>enable</Nullable>
    <WarningLevel>8</WarningLevel>
    <LangVersion>13</LangVersion>
    <EnableDefaultApplicationDefinition>false</EnableDefaultApplicationDefinition>
    <Title>AutoTanpopo</Title>
    <Version>0.1.0</Version>
    <Authors>koturn</Authors>
    <Copyright>Copyright (C) 2023 koturn All Rights Reserverd.</Copyright>
    <Description>An application to automatically place dandelions in VRChat.</Description>
    <PackageProjectUrl>https://github.com/koturn/AutoTanpopo</PackageProjectUrl>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageTags>WPF;VRChat;Win32API</PackageTags>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="Resources\tanpopo.ico" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\LICENSE">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include="..\README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Koturn.Windows.AppWindows\Koturn.Windows.AppWindows\Koturn.Windows.AppWindows.csproj" />
    <ProjectReference Include="..\Koturn.Windows.HotKeys\Koturn.Windows.HotKeys\Koturn.Windows.HotKeys.csproj" />
    <ProjectReference Include="..\Koturn.Windows.Inputs\Koturn.Windows.Inputs\Koturn.Windows.Inputs.csproj" />
  </ItemGroup>

</Project>
